# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    
  config.ssh.insert_key = false

  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.box="shekeriev/debian-11"
    jenkins.vm.hostname = "pipelines.retake.exam"
    jenkins.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "3072"]
    end
    jenkins.vm.network "private_network", ip: "192.168.121.121"
    jenkins.vm.network "forwarded_port", guest: 8080, host: 8080
    jenkins.vm.provision "shell", path: "install_common.sh"
	jenkins.vm.provision "shell", path: "install_jenkins.sh"
  end
  
  config.vm.define "docker" do |docker|
    docker.vm.box="shekeriev/debian-11"
    docker.vm.hostname = "containers.retake.exam"
    docker.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "3072"]
    end
    docker.vm.network "private_network", ip: "192.168.121.122"
    docker.vm.network "forwarded_port", guest: 8080, host: 8081
	docker.vm.network "forwarded_port", guest: 3000, host: 9090
    docker.vm.provision "shell", path: "install_common.sh"
    docker.vm.provision "shell", path: "install_docker.sh"
  end
  
  config.vm.define "promgraf" do |promgraf|
    promgraf.vm.box="shekeriev/debian-11"
    promgraf.vm.hostname = "monitoring.retake.exam"
    promgraf.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "3072"]
    end
    promgraf.vm.network "private_network", ip: "192.168.121.123"
    promgraf.vm.network "forwarded_port", guest: 3000, host: 8082
  end

end
